package org.schabi.newpipe.player.resolver;

import static com.google.android.exoplayer2.C.TIME_UNSET;
import static org.schabi.newpipe.util.ListHelper.getFilteredAudioStreams;
import static org.schabi.newpipe.util.ListHelper.getPlayableStreams;
import static org.schabi.newpipe.util.ListHelper.getUrlAndNonTorrentStreams;

import android.content.Context;
import android.net.Uri;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.MergingMediaSource;

import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.stream.AudioStream;
import org.schabi.newpipe.extractor.stream.Stream;
import org.schabi.newpipe.extractor.stream.StreamInfo;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import org.schabi.newpipe.extractor.stream.VideoStream;
import org.schabi.newpipe.player.helper.PlayerDataSource;
import org.schabi.newpipe.player.helper.PlayerHelper;
import org.schabi.newpipe.player.mediaitem.MediaItemTag;
import org.schabi.newpipe.player.resolver.PlaybackResolver.ResolverException;
import org.schabi.newpipe.util.ListHelper;

import java.util.ArrayList;
import java.util.List;

/** Production adapter for Android preferences and ExoPlayer source construction. */
final class AndroidPlaybackEnvironment implements PlaybackSources.Environment {
    private static final String TAG = PlaybackSources.class.getSimpleName();
    @NonNull
    private final Context context;
    @NonNull
    private final PlayerDataSource dataSource;

    AndroidPlaybackEnvironment(@NonNull final Context context,
                               @NonNull final PlayerDataSource dataSource) {
        this.context = context;
        this.dataSource = dataSource;
    }

    @Override
    public List<VideoStream> sortedVideoStreams(final StreamInfo info) {
        return ListHelper.getSortedStreamVideosList(context,
                getPlayableStreams(info.getVideoStreams(), info.getServiceId()),
                getPlayableStreams(info.getVideoOnlyStreams(), info.getServiceId()), false, true);
    }

    @Override
    public List<VideoStream> audioFallbackStreams(final StreamInfo info) {
        return getPlayableStreams(info.getVideoStreams(), info.getServiceId());
    }

    @Override
    public List<AudioStream> audioStreams(final StreamInfo info) {
        return getFilteredAudioStreams(context, info.getAudioStreams());
    }

    @Override
    public int audioIndex(final List<AudioStream> streams, @Nullable final String audioTrack) {
        return ListHelper.getAudioFormatIndex(context, streams, audioTrack);
    }

    @Override
    public int audioFallbackIndex(final List<VideoStream> streams) {
        return ListHelper.getDefaultResolutionIndex(context, streams);
    }

    @Override
    @Nullable
    public MediaSource liveSource(final StreamInfo info) {
        return PlaybackResolver.maybeBuildLiveMediaSource(dataSource, info);
    }

    @Override
    public MediaSource streamSource(final StreamInfo info,
                                    @Nullable final Stream stream,
                                    final MediaItemTag tag) throws ResolverException {
        return PlaybackResolver.buildMediaSource(dataSource, stream, info,
                PlaybackResolver.cacheKeyOf(info, stream), tag);
    }

    @Override
    public List<MediaSource> subtitleSources(final StreamInfo info) {
        final List<MediaSource> sources = new ArrayList<>();
        final List<SubtitlesStream> subtitles = info.getSubtitles();
        if (subtitles != null) {
            for (final SubtitlesStream subtitle : getUrlAndNonTorrentStreams(subtitles)) {
                final MediaFormat format = subtitle.getFormat();
                if (format != null) {
                    @C.RoleFlags final int role = subtitle.isAutoGenerated()
                            ? C.ROLE_FLAG_DESCRIBES_MUSIC_AND_SOUND : C.ROLE_FLAG_CAPTION;
                    final MediaItem.SubtitleConfiguration configuration =
                            new MediaItem.SubtitleConfiguration.Builder(
                                    Uri.parse(subtitle.getContent()))
                                    .setMimeType(format.getMimeType())
                                    .setRoleFlags(role)
                                    .setLanguage(PlayerHelper.captionLanguageOf(context, subtitle))
                                    .build();
                    sources.add(dataSource.getSingleSampleMediaSourceFactory()
                            .createMediaSource(configuration, TIME_UNSET));
                }
            }
        }
        return sources;
    }

    @Override
    public MediaSource merge(final List<MediaSource> sources) {
        return new MergingMediaSource(true, sources.toArray(new MediaSource[0]));
    }

    @Override
    public void logError(final String message, final Exception error) {
        Log.e(TAG, message, error);
    }

    @Override
    public void logWarning(final String message) {
        Log.w(TAG, message);
    }
}
